[2024-10-13T02:50:40.660-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-13T02:50:40.679-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T06:49:58.767396+00:00 [queued]>
[2024-10-13T02:50:40.688-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T06:49:58.767396+00:00 [queued]>
[2024-10-13T02:50:40.688-0400] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-13T02:50:40.706-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_task> on 2024-10-13 06:49:58.767396+00:00
[2024-10-13T02:50:40.716-0400] {standard_task_runner.py:72} INFO - Started process 16505 to run task
[2024-10-13T02:50:40.723-0400] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-13T02:50:40.734-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bixi_etl_pipeline', 'transform_task', 'manual__2024-10-13T06:49:58.767396+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/bixi_etl_pipeline.py', '--cfg-path', '/var/folders/bj/4z3t139j7xj2qng4wk4y16ym0000gn/T/tmpqcilh63z']
[2024-10-13T02:50:40.736-0400] {standard_task_runner.py:105} INFO - Job 163: Subtask transform_task
[2024-10-13T02:50:40.815-0400] {task_command.py:467} INFO - Running <TaskInstance: bixi_etl_pipeline.transform_task manual__2024-10-13T06:49:58.767396+00:00 [running]> on host karendembp.home
[2024-10-13T02:50:41.286-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bixi_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T06:49:58.767396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T06:49:58.767396+00:00'
[2024-10-13T02:50:41.289-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-13T02:50:41.290-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-13T02:50:41.291-0400] {logging_mixin.py:190} INFO - Current task name:transform_task state:running start_date:2024-10-13 06:50:40.679910+00:00
[2024-10-13T02:50:41.292-0400] {logging_mixin.py:190} INFO - Dag name:bixi_etl_pipeline and current dag run status:running
[2024-10-13T02:50:41.293-0400] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-13T02:50:53.841-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 78, in transform_data
    df_combined.write.mode("overwrite").parquet(temp_parquet_path)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
    self._jwrite.parquet(path)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `is_charging` already exists. Consider to choose another name or rename the existing column.
[2024-10-13T02:50:53.861-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-13T02:50:53.863-0400] {logging_mixin.py:190} INFO - Task start:2024-10-13 06:50:40.679910+00:00 end:2024-10-13 06:50:53.861218+00:00 duration:13.181308
[2024-10-13T02:50:53.864-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_task> dag:<DAG: bixi_etl_pipeline> dagrun:<DagRun bixi_etl_pipeline @ 2024-10-13 06:49:58.767396+00:00: manual__2024-10-13T06:49:58.767396+00:00, state:running, queued_at: 2024-10-13 06:49:58.800096+00:00. externally triggered: True>
[2024-10-13T02:50:53.871-0400] {logging_mixin.py:190} INFO - Failure caused by [COLUMN_ALREADY_EXISTS] The column `is_charging` already exists. Consider to choose another name or rename the existing column.
[2024-10-13T02:50:53.873-0400] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=bixi_etl_pipeline, task_id=transform_task, run_id=manual__2024-10-13T06:49:58.767396+00:00, execution_date=20241013T064958, start_date=20241013T065040, end_date=20241013T065053
[2024-10-13T02:50:53.893-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-13T02:50:53.894-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 163 for task transform_task ([COLUMN_ALREADY_EXISTS] The column `is_charging` already exists. Consider to choose another name or rename the existing column.; 16505)
Traceback (most recent call last):
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/karenwang/airflow/dags/bixi_etl_pipeline.py", line 78, in transform_data
    df_combined.write.mode("overwrite").parquet(temp_parquet_path)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1721, in parquet
    self._jwrite.parquet(path)
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/Users/karenwang/anaconda3/envs/airflow_sqlite_env/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [COLUMN_ALREADY_EXISTS] The column `is_charging` already exists. Consider to choose another name or rename the existing column.
[2024-10-13T02:50:53.948-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-13T02:50:53.975-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T02:50:54.006-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
